import { IBM_Plex_Mono } from "next/font/google";
import Navbar from "./_components/navbar";
import "./_styles/globals.css";
import Footer from "./_components/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const IBMPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  // weight: "700",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={IBMPlexMono.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
